export const path = {
    ROOT: '/',
    HOME: '',
    LOGIN: 'login',
    PHIM_BO: 'phim-bo',
    PHIM_LE: 'phim-le',
    TV_SHOWS: 'tv-shows',
    CAR_TOON: 'hoat-hinh',
    THE_LOAI: "the-loai",
    THE_LOAI_PHIM: "the-loai/:filmCategory",
    DETAIL_FILM: "chi-tiet-phim/:filmName",
    COUNTRY: 'quoc-gia',
    COUNTRY_FILM: 'quoc-gia/:countryFilm',
    WATCH_FILM: 'xem-phim/:filmName',
    FILTER_FILM: 'sort/:listFilm',
    SEARCH_FILM: 'tim-kiem',
}